# Generated by Django 5.2.16 on 2026-07-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_email_verified_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(choices=[('verification', 'Verification'), ('password_reset', 'Password Reset')], default='verification', max_length=20),
        ),
    ]
