# Generated by Django 5.2.16 on 2026-08-01 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capsules', '0005_capsule_has_been_opened_capsule_opened_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capsule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reflection', to='capsules.capsule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReflectionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reflection_attachments/')),
                ('attachment_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reflection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reflections.reflection')),
            ],
        ),
    ]
