# Generated by Django 5.2.16 on 2026-07-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capsule',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='capsule',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='capsule',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='capsule_type',
            field=models.CharField(choices=[('memory', 'Memory'), ('prediction', 'Prediction'), ('accountability', 'Accountability'), ('gift', 'Gift')], default='memory', max_length=20),
        ),
    ]
