# Generated by Django 5.2.16 on 2026-07-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0002_capsule_delivered_at_capsule_is_delivered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='capsule_type',
            field=models.CharField(choices=[('memory', 'Memory'), ('prediction', 'Prediction'), ('accountability', 'Accountability'), ('letter', 'Letter')], default='memory', max_length=20),
        ),
    ]
