# Generated by Django 5.2.16 on 2026-08-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0004_alter_attachment_id_alter_capsule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='has_been_opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='capsule',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
