# Generated by Django 5.2.16 on 2026-08-01 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0005_capsule_has_been_opened_capsule_opened_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='parent_capsule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_capsules', to='capsules.capsule'),
        ),
    ]
