# Generated by Django 5.2.16 on 2026-08-01 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0006_capsule_parent_capsule'),
        ('reflections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='reflection_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='future_capsules', to='reflections.reflection'),
        ),
    ]
